// Tooling lives outside harness/web and is never served by the daemon.
import { spawnSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const directory = new URL("./", import.meta.url);
const python = process.env.PYTHON || "python";
const exported = spawnSync(python, [fileURLToPath(new URL("export_schema.py", directory))], { encoding: "utf8", env: { ...process.env, PYTHONIOENCODING: "utf-8" } });
if (exported.status !== 0) {
  throw new Error(`OpenAPI export failed: ${exported.error || exported.stderr}`);
}
const schema = JSON.parse(exported.stdout);
const outputs = {
  "openapi.json": JSON.stringify(schema, null, 2) + "\n",
  "api.d.ts": "/** Generated by npm run generate; do not edit. */\n" + astToString(await openapiTS(schema, { defaultNonNullable: false })),
};
for (const [name, content] of Object.entries(outputs)) {
  const path = new URL(name, directory);
  if (process.argv.includes("--check")) {
    const existing = await readFile(path, "utf8").catch(() => "");
    if (existing !== content) throw new Error(`${name} is stale. Run npm --prefix tools/web-types run generate.`);
  } else {
    await writeFile(path, content);
  }
}
